---
## ROLE GATEWAY VARS ##
nat_cidr: 10.0.0.0/24
nat_interface: eth1
nat_server_ip: 10.0.0.1

## ROLE NAMED VARS ##
bind_acls:
  - name: trusted
    match_list:
      - 127.0.0.1
      - 10.0.0.0/24
bind_allow_query:
  - trusted
bind_forwarders:
  - 62.210.16.6
  - 62.210.16.7
bind_listen_ipv4:
  - 127.0.0.1
  - 10.0.0.1
bind_recursion: true
bind_dnssec_enable: false
bind_dnssec_validation: false
bind_zone_domains:
  - name: sd-51798.dy2k.io
    networks:
      - 10.0.0
    name_servers:
      - ns1.sd-51798.dy2k.io.
      - ns2.sd-51798.dy2k.io.
    hostmaster_email: admin
    hosts:
      - name: ns1
        ip: 10.0.0.1
      - name: ns2
        ip: 10.0.0.2
      - name: gateway1
        ip: 10.0.0.1
      - name: gateway2
        ip: 10.0.0.2
      - name: kube-cluster1
        ip: 10.0.0.10
      - name: kube-master1
        ip: 10.0.0.11
      - name: kube-master2
        ip: 10.0.0.12
      - name: kube-master3
        ip: 10.0.0.13
      - name: kube-worker1
        ip: 10.0.0.21
      - name: kube-worker2
        ip: 10.0.0.22
      - name: kube-worker3
        ip: 10.0.0.23
bind_zone_master_server_ip: 10.0.0.1

## ROLE LOADBALANCER VARS ##
loadbalancer_haproxy_address: 10.0.0.10
loadbalancer_haproxy_port: 6443

haproxy_firewalld: false
haproxy_selinux: false

haproxy_default_mode: http

haproxy_stats_address: 10.0.0.10
haproxy_stats_port: 1080
haproxy_stats_user: admin
haproxy_stats_password: "{{ loadbalancer_haproxy_password }}"
haproxy_stats_uri: /admin?stats
haproxy_stats_options:
  - refresh 5s

haproxy_frontend:
  - kube_apiserver_frontend:
      mode: tcp
      binds:
        - "{{ loadbalancer_haproxy_address }}:{{ loadbalancer_haproxy_port }}"
      options:
        - tcplog
      default_backend: kube_apiserver_backend

haproxy_backend:
  - kube_apiserver_backend:
      mode: tcp
      method: roundrobin
      servers:
        - kube-master1 10.0.0.11:6443 check
        - kube-master2 10.0.0.12:6443 check
        - kube-master3 10.0.0.13:6443 check

# keepalived_scripts:
#   haproxy_check_script:
#     check_script: killall -0 haproxy
#     interval: 3
#     fall: 10
#     rise: 2
#     weight: -2

keepalived_instances:
  internal:
    interface: eth0
    state: MASTER
    virtual_router_id: 1
    priority: 100
    authentication_password: "{{ loadbalancer_keepalived_password }}"
    #     track_scripts:
    #       - haproxy_check_script
    vips:
      - 10.0.0.10

## ROLE COMMON VARS ##
zabbix_agent_type: zabbix2
zabbix_endpoints_passive: zabbix-server
zabbix_endpoints_active: zabbix-server:10051

## ROLE RUNTIME VARS ##
runtime_type: containerd
debug: false

## ROLE KUBRADM VARS ##
kubeadm_pull_images: false
kubeadm_version: v1.33
kubeadm_load_balancer_dns: kube-cluster1.sd-51798.dy2k.io
kubeadm_load_balancer_port: 6443
kubeadm_pod_network_cidr: 10.244.0.0/16
kubeadm_cni_plugins:
  name: calico
  sources:
    - url: https://raw.githubusercontent.com/projectcalico/calico/v3.30.0/manifests/calico.yaml
      dest: /tmp/calico.yaml
  modifications: []
