---
kubeadm_pull_images: false
kubeadm_version: v1.31
kubeadm_load_balancer_dns: kube-cluster1.sd-51798.dy2k.io
kubeadm_load_balancer_port: 6443
kubeadm_pod_network_cidr: 10.244.0.0/16
kubeadm_cni_plugins:
  name: calico
  sources:
    - url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/calico.yaml
      dest: /tmp/calico.yaml
  modifications: []