---
- name: Download zabbix package
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    dest: /home/terraform/zabbix-release_6.4-1+ubuntu22.04_all.deb
    owner: root
    group: root
    mode: "0775" # Read/write for owner, read/execute for group/others

- name: Install zabbix package
  ansible.builtin.command: dpkg -i /home/terraform/zabbix-release_6.4-1+ubuntu22.04_all.deb
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install zabbix-agent-2
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present

- name: Configure Zabbix
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "# SourceIP=", line: "SourceIP={{ ansible_default_ipv4.address }}" }
    - { regexp: Server=127.0.0.1, line: "Server={{ zabbix_endpoints_passive }}" }
    - { regexp: "# ListenIP=0.0.0.0", line: "ListenIP={{ ansible_default_ipv4.address }}" }
    - { regexp: ServerActive=127.0.0.1, line: "ServerActive={{ zabbix_endpoints_active }}" }
    - { regexp: Hostname=Zabbix server, line: "Hostname={{ ansible_hostname }}" }

- name: Enable and Restart Zabbix
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: true
