---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
    enabled: true

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system

- name: Restart System Modules Load
  ansible.builtin.service:
    name: systemd-modules-load
    state: restarted
