---
- name: Get architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: os_architecture

- name: Get OS release
  ansible.builtin.shell:
    cmd: . /etc/os-release && echo "$VERSION_CODENAME"
  register: os_release

- name: Get OS Type
  ansible.builtin.shell:
    cmd: . /etc/os-release && echo "$ID"
  register: os_type

- name: Uninstall Docker old versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  notify:
    - Refresh APT cache

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ os_type.stdout }}/gpg

- name: Set up Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ os_architecture.stdout }}] https://download.docker.com/linux/{{ os_type.stdout }} {{ os_release.stdout }} stable

- name: Install Docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Check Docker systemd directory
  ansible.builtin.stat:
    path: /etc/systemd/system/docker.service.d
  register: runtime_docker_systemd

- name: Create Docker systemd directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0755" # Read/write for owner, read/execute for group/others
    owner: root
    group: root
  when: not runtime_docker_systemd.stat.exists

- name: Set up Docker daemon
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0644" # Read/write for owner, read-only for others
    owner: root
    group: root
  notify: Restart Docker

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
