---
- name: Install kubeadm dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl
      - ca-certificates
      - gnupg

- name: Check if the repository list exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kubernetes.list
  register: repo_stat

- name: Check if the repository key exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: key_stat

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Delete old repo keys
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent
  when: key_stat.stat.exists

- name: Download Kubernetes APT key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubeadm_version }}/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'
  when: not repo_stat.stat.exists

- name: Convert key to GPG format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  when: not repo_stat.stat.exists

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubeadm_version }}/deb/ /
    filename: kubernetes
    state: present
  when: not repo_stat.stat.exists

- name: Install kubeadm executables
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
  notify: Mark kubeadm executables as hold

- name: Check Kubernetes component statuses
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.shell:
    cmd: >
      set -o pipefail
      kubectl get componentstatuses 2>&1 | grep Healthy | wc -l || true
  register: kubeadm_components
  changed_when: false
  when: inventory_hostname == groups["masters"][0]

- name: Check kubernetes join statuses
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.shell:
    cmd: >
      set -o pipefail
      kubectl get nodes -o wide | grep {{ inventory_hostname }} | tr -s ' ' | cut -d ' ' -f2 | wc -l || true
  register: kubeadm_join_status
  changed_when: false
  delegate_to: '{{ groups["masters"][0] }}'

- name: Register Kubernetes certificate key
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      kubeadm certs certificate-key || true
  register: kubeadm_certificate_key
  changed_when: false
  when: inventory_hostname == groups["masters"][0]

- name: Set fact for certificate key
  run_once: true
  ansible.builtin.set_fact:
    kubeadm_certificate_key: '"{{ kubeadm_certificate_key.stdout }}"'
  when: inventory_hostname == groups["masters"][0]

- name: Check Kubernetes join token
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      kubeadm token list | grep bootstrap | cut -d ' ' -f1 | head -n 1 || true
  register: kubeadm_join_token
  changed_when: false
  when: inventory_hostname == groups["masters"][0]

- name: Generate Kubernetes join token
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.command: kubeadm token generate
  register: kubeadm_join_token_create
  when: inventory_hostname == groups["masters"][0] and kubeadm_join_token.stdout == ''

- name: Create Kubernetes join token
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.shell: kubeadm token create 2>/dev/null || true
  when: inventory_hostname == groups["masters"][0] and kubeadm_components.stdout|int >=1 and kubeadm_join_token.stdout == ''

- name: Set fact for existing Kubernetes join token
  run_once: true
  ansible.builtin.set_fact:
    kubeadm_join_token: '"{{ kubeadm_join_token.stdout }}"'
  when: inventory_hostname == groups["masters"][0] and not kubeadm_join_token_create.changed

- name: Set fact for created Kubernetes join token
  run_once: true
  ansible.builtin.set_fact:
    kubeadm_join_token: '"{{ kubeadm_join_token_create.stdout }}"'
  when: inventory_hostname == groups["masters"][0] and kubeadm_join_token_create.changed

- name: Pull the kubernetes container images
  ansible.builtin.command: kubeadm config images pull
  when: kubeadm_pull_images and '"masters" in group_names'

# Clean Primary Node 
# kubeadm reset --cleanup-tmp-dir --force && m -r .kube/
- name: DEBUG init primary kubernetes node command
  ansible.builtin.debug:
    msg: >
      "kubeadm init
      --control-plane-endpoint {{ kubeadm_load_balancer_dns }}:{{ kubeadm_load_balancer_port }}
      --pod-network-cidr {{ kubeadm_pod_network_cidr }}
      --token {{ kubeadm_join_token }}
      --certificate-key {{ kubeadm_certificate_key }}
      --cri-socket /run/containerd/containerd.sock
      {% if debug %}
      --v=5
      {% endif %}"
  when: inventory_hostname == groups["masters"][0] and debug

- name: DEBUG ALL VARS
  ansible.builtin.debug:
    msg:
      - "kubeadm_version: {{ kubeadm_version }}"
      - "kubeadm_components: {{ kubeadm_components }}"
      - "kubeadm_join_status: {{ kubeadm_join_status }}"
      - "kubeadm_certificate_key: {{ kubeadm_certificate_key }}"
      - "kubeadm_join_token: {{ kubeadm_join_token }}"
      - "kubeadm_join_token_create: {{ kubeadm_join_token_create }}"
      - "kubeadm_pull_images: {{ kubeadm_pull_images }}"
  when: inventory_hostname == groups["masters"][0] and debug

- name: Init primary Kubernetes control plane
  ansible.builtin.command: >
    kubeadm init
    --control-plane-endpoint {{ kubeadm_load_balancer_dns }}:{{ kubeadm_load_balancer_port }}
    --pod-network-cidr {{ kubeadm_pod_network_cidr }}
    --token {{ kubeadm_join_token }}
    --certificate-key {{ kubeadm_certificate_key }}
    --cri-socket /run/containerd/containerd.sock
    {% if debug %}
    --v=5
    {% endif %}
  when: inventory_hostname == groups["masters"][0] and kubeadm_components.stdout|int < 1
  timeout: 300
  register: kubeadm_init_result

- name: Generate kubeadm-certs secret
  ansible.builtin.command: kubeadm init phase upload-certs --upload-certs --certificate-key {{ kubeadm_certificate_key }}
  when: inventory_hostname == groups["masters"][0]

- name: Register Kubernetes discovery token ca cert hash
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
      openssl rsa -pubin -outform der 2>/dev/null |  openssl dgst -sha256 -hex | sed 's/^.* //' || true
  register: kubeadm_discovery_token_ca_cert_hash
  changed_when: false
  when: inventory_hostname == groups["masters"][0]

- name: Set fact for Kubernetes discovery token ca cert hash
  run_once: true
  ansible.builtin.set_fact:
    kubeadm_discovery_token_ca_cert_hash: '"{{ kubeadm_discovery_token_ca_cert_hash.stdout }}"'
  when: inventory_hostname == groups["masters"][0]

- name: Check Kubernetes network configurations
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.shell:
    cmd: >
      set -o pipefail
      kubectl get all -n kube-system 2>&1 | grep {{ kubeadm_cni_plugins.name }} | wc -l || true
  register: kubeadm_network
  changed_when: false
  when: inventory_hostname == groups["masters"][0]

- name: Download network configurations
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    force: true
    owner: root
    group: root
    mode: "0644" # Read/write for owner, read-only for others
  loop: "{{ kubeadm_cni_plugins.sources }}"
  when: inventory_hostname == groups["masters"][0] and kubeadm_network.stdout|int < 1

- name: Modify network configurations
  ansible.builtin.command: sed -i -e '{{ item.args }}' {{ item.file }}
  loop: "{{ kubeadm_cni_plugins.modifications }}"
  when:
    inventory_hostname == groups["masters"][0] and kubeadm_network.stdout|int < 1 and
    kubeadm_cni_plugins.modifications is defined and kubeadm_cni_plugins.modifications|length > 0

- name: Apply network configurations
  ansible.builtin.command: kubectl apply -f {{ item.dest }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  loop: "{{ kubeadm_cni_plugins.sources }}"
  when: inventory_hostname == groups["masters"][0] and kubeadm_network.stdout|int < 1

- name: Join the rest of Kubernetes control plane nodes
  ansible.builtin.command: >
    kubeadm join --v=5 {{ kubeadm_load_balancer_dns }}:{{ kubeadm_load_balancer_port }} --control-plane --token {{ kubeadm_join_token }}
    --discovery-token-ca-cert-hash sha256:{{ kubeadm_discovery_token_ca_cert_hash }} --certificate-key {{ kubeadm_certificate_key }}
  when: kubeadm_join_status.stdout|int < 1 and inventory_hostname != groups["masters"][0] and "masters" in group_names

- name: Join the rest of Kubernetes worker nodes
  ansible.builtin.command: >
    kubeadm join {{ kubeadm_load_balancer_dns }}:{{ kubeadm_load_balancer_port }}
    --token {{ kubeadm_join_token }} --discovery-token-ca-cert-hash sha256:{{ kubeadm_discovery_token_ca_cert_hash }}
  when: kubeadm_join_status.stdout|int < 1 and "workers" in group_names

- name: Check kubernetes join statuses
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.shell: |
    set -o pipefail
    kubectl get nodes -o wide | grep {{ inventory_hostname }} | tr -s ' ' | cut -d ' ' -f2 | wc -l || true
  register: kubeadm_join_status
  changed_when: false
  delegate_to: '{{ groups["masters"][0] }}'

- name: Ensure kube config directory exists
  ansible.builtin.file:
    path: /home/terraform/.kube
    state: directory
    owner: terraform
    group: terraform
    mode: "0644" # Read/write for owner, read-only for others

- name: Copy admin.conf for Kubernetes control plane nodes
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/terraform/.kube/config
    owner: terraform
    group: terraform
    mode: "0644" # Read/write for owner, read-only for others
    remote_src: true
  when: kubeadm_join_status.stdout|int >= 1 and "masters" in group_names

- name: Copy kubelet.conf for Kubernetes worker nodes
  ansible.builtin.copy:
    src: /etc/kubernetes/kubelet.conf
    dest: /home/terraform/.kube/config
    owner: terraform
    group: terraform
    mode: "0644" # Read/write for owner, read-only for others
    remote_src: true
  when: kubeadm_join_status.stdout|int >= 1 and "workers" in group_names
