---
- name: Copy kube config
  ansible.builtin.command: cat .kube/config
  register: kube_config
  when: inventory_hostname == groups["masters"][0]

- name: Paste kube config
  ansible.builtin.copy:
    content: "{{ kube_config.stdout }}"
    dest: ../kube/config
    mode: "0644" # Read/write for owner, read-only for others
  delegate_to: localhost # 127.0.0.1
  run_once: true
